### ISSUE TITLE
Twitch Chat Bot: KeyError on a Clear chat event

### ISSUE THREAD

**Issue by stolenvw** [Teekeks/pyTwitchAPI#194]
```
2023-01-22 16:49:44 - ERROR - asyncio: Task exception was never retrieved
future: <Task finished name='Task-2434' coro=<Chat._handle_clear_chat() done, defined at /home/user/test-twitch-bot/.twitchtestenv/lib/python3.10/site-packages/twitchAPI/chat.py:890> exception=KeyError('ban-duration')>
Traceback (most recent call last):
  File "/home/user/test-twitch-bot/.twitchtestenv/lib/python3.10/site-packages/twitchAPI/chat.py", line 891, in _handle_clear_chat
    e = ClearChatEvent(self, parsed)
  File "/home/user/test-twitch-bot/.twitchtestenv/lib/python3.10/site-packages/twitchAPI/chat.py", line 488, in __init__
    self.duration: Optional[int] = int(parsed['tags']['ban-duration']) if parsed['tags']['ban-duration'] not in (None, '') else None
KeyError: 'ban-duration'
```

Did not have debug logging on for `twitchAPI.chat` , happened after a users messages where deleted.

**Comment by Teekeks** [comment]
Fix is available on pypi, version 3.5.1
