### ISSUE TITLE
OSError: [Errno 99] error while attempting to bind on address ('::1', 17563, 0, 0): cannot assign requested address

### ISSUE THREAD

**Issue by Arthurdw** [Teekeks/pyTwitchAPI#5]
I was trying to run the example WebSocket code and it crashes on this:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/twitchAPI/oauth.py", line 103, in __run
    self.__loop.run_until_complete(site.start())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_runner.py", line 104, in start
    reuse_port=self._reuse_port)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1374, in create_server
    % (sa, err.strerror.lower())) from None
OSError: [Errno 99] error while attempting to bind on address ('::1', 17563, 0, 0): cannot assign requested address
```
The example I used [can be found here](https://github.com/Teekeks/pyTwitchAPI/blob/master/webhook_example.py)

**Comment by Teekeks** [comment]
Can you give me the exact code you tried to run? Also could it be that there is still a process running that is blocking the port 17563?

**Comment by Arthurdw** [comment]
The code was an exact copy. (except that I replaced the client id and secrets with mine. No other proces was running on that port.

**Comment by Teekeks** [comment]
Hmm ok which OS and which python version are you using?

**Comment by Arthurdw** [comment]
```
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
```

**Comment by Teekeks** [comment]
This seems to be related to some local service already using that port. Cant fix this.
