### ISSUE TITLE
get_clips function does not work for clip_id's

### ISSUE THREAD

**Issue by nikshepsvn** [Teekeks/pyTwitchAPI#65]
As an example
```
twitch.get_clips(clip_id=["SeductiveInspiringTroutKappa"])
```
the following functions fails with
```
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    a = TwitchHelper().twitch.get_clips(clip_id=["SeductiveInspiringTroutKappa"])
  File "/Users/nikshepsvn/PycharmProjects/twitch/venv/lib/python3.7/site-packages/twitchAPI/twitch.py", line 675, in get_clips
    result = self.__api_get_request(url, AuthType.APP, [])
  File "/Users/nikshepsvn/PycharmProjects/twitch/venv/lib/python3.7/site-packages/twitchAPI/twitch.py", line 333, in __api_get_request
    raise TwitchAPIException('Bad Request')
twitchAPI.types.TwitchAPIException: Bad Request

```

**Comment by nikshepsvn** [comment]
Realized that slug was a bad one, still errors with a valid slug.
Link to clip: 
https://www.twitch.tv/hachubby/clip/BitterCleverGoldfishEleGiggle--PW-MYiDBUXwTQw1
Call
```
twitch.get_clips(clip_id=["BitterCleverGoldfishEleGiggle--PW-MYiDBUXwTQw1"])
```
Error
```
Traceback (most recent call last):
  File "main.py", line 149, in <module>
    a = TwitchHelper().twitch.get_clips(clip_id=["BitterCleverGoldfishEleGiggle--PW-MYiDBUXwTQw1"])
  File "/Users/nikshepsvn/PycharmProjects/twitch/venv/lib/python3.7/site-packages/twitchAPI/twitch.py", line 675, in get_clips
    result = self.__api_get_request(url, AuthType.APP, [])
  File "/Users/nikshepsvn/PycharmProjects/twitch/venv/lib/python3.7/site-packages/twitchAPI/twitch.py", line 333, in __api_get_request
    raise TwitchAPIException('Bad Request')
twitchAPI.types.TwitchAPIException: Bad Request
```

**Comment by Teekeks** [comment]
Yes, looks like they either changed the parameter name or I fucked up. Will push a fix in a few minutes.

**Comment by nikshepsvn** [comment]
Sounds good, I think the param now is `id` instead of `clip_id`

**Comment by nikshepsvn** [comment]
Want me to push a change?

**Comment by Teekeks** [comment]
No I am already on finalizing that hotfix :)

**Comment by nikshepsvn** [comment]
Sounds good, thanks!

**Comment by Teekeks** [comment]
Now available via PyPi :)
