### ISSUE TITLE
ngrok with EventSub - need Help

### ISSUE THREAD

**Issue by faildproject** [Teekeks/pyTwitchAPI#85]
Hello,
i want to test EventSub. So I've used ngrok and call it with:
`ngrok http 80`
Its running and give me Forwarding urls: 
[http/https]TheLongUrl.ngrok.io -> http://localhost:80 (use https-form as WEBHOOK_URL)
Now in my script (running on localhost- Windows10-Machine) i called:
```
# Setup the Target-Scope
target_scope = [AuthScope.BITS_READ, 
                AuthScope.CHANNEL_SUBSCRIPTIONS,
                AuthScope.CHANNEL_READ_REDEMPTIONS,
                AuthScope.CHAT_READ,
                AuthScope.CHAT_EDIT,
                AuthScope.CHANNEL_READ_HYPE_TRAIN,
                AuthScope.WHISPERS_READ]
...
eventsub = EventSub(WEBHOOK_URL, keys.APP_ID,80, twitch)
eventsub.unsubscribe_all()
eventsub.listen_channel_points_custom_reward_update(user_id, on_rewardChange)
...
```
ngrok says:
`POST /callback                 502 Bad Gateway`

Python-Script:
```
subscribing to hooks:
Traceback (most recent call last):
  File "c:\Users\faildproject\Documents\Repos\TwitchMQTT\main.py", line 134, in <module>
    eventsub.listen_channel_points_custom_reward_update(user_id, on_rewardChange)
  File "C:\Users\faildproject\Documents\Repos\TwitchMQTT\.venv\lib\site-packages\twitchAPI\eventsub.py", line 583, in listen_channel_points_custom_reward_update      
    return self._subscribe('channel.channel_points_custom_reward.update',
  File "C:\Users\faildproject\Documents\Repos\TwitchMQTT\.venv\lib\site-packages\twitchAPI\eventsub.py", line 253, in _subscribe
    raise EventSubSubscriptionTimeout()
twitchAPI.types.EventSubSubscriptionTimeout
```
When I run SocketTest and Listen on Port 80 I've got the Messages from ngrok-tunnel.
So I think Python didn't receive any Message and can't handle the magic?

Is there any misunderstanding from my side? Can everyone point me the right way?

Thank you Guys, you did a nice Work.

**Comment by d7415** [comment]
As a quick debug step, maybe try listening on port 8080 instead of 80 (and change the forwarding accordingly). There may be restrictions on port 80, though I'm not very familiar with such things in Windows.

**Comment by faildproject** [comment]
I try it with difrent Ports i.e. 2020,8080,4041 everything the same ... Bad Gateway
I also deactivate the Firewall for testing. Must i open the Port in my Router and direct them to my Localhost?

When i list the open Ports of my Localmachine while pyScript is running, I didnt find any of the testet Ports.

**Comment by Teekeks** [comment]
Can you access https://TheLongUrl.ngrok.io/ and what does that return, also bad gateway?

**Comment by faildproject** [comment]
This is the Response as HTML-Formated output:

```
The connection to https://TheLongUrl.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.

Make sure that a web service is running on localhost:80 and that it is a valid address.

The error encountered was: dial tcp [::1]:80: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte. 
```

**Comment by d7415** [comment]
> Must i open the Port in my Router and direct them to my Localhost?

My understanding is that ngrok handles that part.

> The error encountered was: dial tcp [::1]:80: connectex: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte.

Connection refused sounds more likely to be firewall than the python side.

It may be relevant that ngrok is trying to connect using IPv6. Maybe try specifying 127.0.0.1 in ngrok?

**Comment by faildproject** [comment]
Sorry Guys, I'am stupid.
forgot to call the `eventsub.start()`

Everything is fine <3
